name: Build and SonarCloud Analysis

on:
  push: 
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: Test & Analyze
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Run tests with coverage
      - name: Run tests
        run: |
          export AWS_ACCESS_KEY="dummy"
          export AWS_SECRET_KEY="dummy"
          export AWS_REGION="us-east-1"
          export MODEL_ID_3="dummy-model"
          export MODEL_PROVIDER_3="dummy-provider"
          PYTHONPATH=src pytest tests/ --cov=src --cov-report=xml:coverage.xml --junitxml=test-report.xml -v

      # Cache SonarCloud packages
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Mohamedabul_DEB-sonar
            -Dsonar.organization=Mohamedabul
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.python.xunit.reportPath=test-report.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
